package com.example.myapplication.models

object AppConfig {
    const val COLL_USERS = "users"
    const val COLL_OUTFITS = "outfits"
    const val COLL_FAVORITES = "favorites"
    const val COLL_APP_META = "appMeta"

    const val PATH_OUTFITS = "outfits"
    const val PATH_PROFILES = "profile_images"

    const val EXTRA_OUTFIT_ID = "OUTFIT_ID"
    const val EXTRA_IMAGE_URL = "IMAGE_URL"
    const val EXTRA_USER_ID = "USER_ID"
    const val EXTRA_FROM_PROFILE = "FROM_PROFILE"
    const val EXTRA_VIBE = "VIBE"
    const val EXTRA_TOP = "TOP"
    const val EXTRA_BOTTOM = "BOTTOM"
    const val EXTRA_JACKET = "JACKET"
    const val EXTRA_SHOES = "SHOES"
    const val EXTRA_JEWELRY = "JEWELRY"
    const val EXTRA_SUNGLASSES = "SUNGLASSES"
    const val EXTRA_BAG = "BAG"
    const val EXTRA_TOP_RGB = "TOP_RGB"
    const val EXTRA_BOTTOM_RGB = "BOTTOM_RGB"
    const val EXTRA_JACKET_RGB = "JACKET_RGB"
    const val EXTRA_SHOES_RGB = "SHOES_RGB"
    const val EXTRA_JEWELRY_RGB = "JEWELRY_RGB"
    const val EXTRA_SUNGLASSES_RGB = "SUNGLASSES_RGB"
    const val EXTRA_BAG_RGB = "BAG_RGB"

    const val FIELD_VIBE = "vibe"
    const val FIELD_VIBE_SEARCH_KEY = "vibeSearchKey"
    const val FIELD_TOP = "top"
    const val FIELD_BOTTOM = "bottom"
    const val FIELD_JACKET = "jacket"
    const val FIELD_SHOES = "shoes"
    const val FIELD_JEWELRY = "jewelry"
    const val FIELD_SUNGLASSES = "sunglasses"
    const val FIELD_BAG = "bag"
    const val FIELD_TOP_RGB = "topRgb"
    const val FIELD_BOTTOM_RGB = "bottomRgb"
    const val FIELD_JACKET_RGB = "jacketRgb"
    const val FIELD_SHOES_RGB = "shoesRgb"
    const val FIELD_JEWELRY_RGB = "jewelryRgb"
    const val FIELD_SUNGLASSES_RGB = "sunglassesRgb"
    const val FIELD_BAG_RGB = "bagRgb"
    /** Legacy outfit documents only */
    const val FIELD_TOP_COLOR_HEX = "topColorHex"
    const val FIELD_BOTTOM_COLOR_HEX = "bottomColorHex"
    const val FIELD_JACKET_COLOR_HEX = "jacketColorHex"
    const val FIELD_SHOES_COLOR_HEX = "shoesColorHex"
    const val FIELD_JEWELRY_COLOR_HEX = "jewelryColorHex"
    const val FIELD_SUNGLASSES_COLOR_HEX = "sunglassesColorHex"
    const val FIELD_BAG_COLOR_HEX = "bagColorHex"
    const val FIELD_IMAGE_URL = "imageUrl"
    const val FIELD_USER_ID = "userId"
    const val FIELD_TIMESTAMP = "timestamp"
    const val FIELD_PERSONAL_PALETTE = "personalPalette"
    /** Saved feed filter preferences on `users/{uid}` (merged map). */
    /** Outfit document ids the user liked — stored on `users/{uid}` (reliable right after signup). */
    const val FIELD_LIKED_OUTFIT_IDS = "likedOutfitIds"
    const val FIELD_FEED_FILTERS = "feedFilters"
    const val FIELD_FEED_FILTER_SELECTED_VIBE = "selectedVibe"
    const val FIELD_FEED_FILTER_MATCH_PALETTE = "matchMyPalette"
    const val DOC_GLOBAL_VIBES = "globalVibes"
    const val FIELD_VALUES = "values"

    const val FILTER_ALL = "ALL"

    val REQUIRED_FIELDS = listOf(FIELD_TOP, FIELD_BOTTOM, FIELD_VIBE)
}
